### ISSUE TITLE
subprocess.CalledProcessError

### ISSUE THREAD

**Issue by maxkrivich** [hamzahmidi/twitch_Bot#1]
In  36 line throw exception in Linux because Popen can't find .exe file. You must add just simple OS check like  ` if os.name == "nt": prog = "livestreamer.exe" else prog = "livestreamer"`. Easy fix.

**Comment by hamzahmidi** [comment]
I have changed it into   "livestreamer" and this will make it work on any ows with the livestreamer binary in thr PATH
